### ISSUE TITLE
Moving the image with a gesture

### ISSUE THREAD

**Issue by Slasar41** [Inareous/Minimal-CS-Manga-Reader#18]
Moving the image with two fingers to the left will result the application to close.
Moving to the right works fine.

**Comment by Inareous** [comment]
I actually cannot test this rigorously as I don't have any touch device, however it shouldn't really be a problem since MCS doesn't manually handle/catch any touch related input.

I tried simulating touch input using Windows Simulator ([1](https://www.marcosikkens.nl/index.php/2018/08/16/simulating-touch-on-windows-10-for-a-wpf-application/), [2](https://docs.microsoft.com/en-us/visualstudio/debugger/run-windows-store-apps-in-the-simulator?view=vs-2019)) but I can't reproduce the issue. Moving two fingers to any direction works normally, can you try with another device?

**Comment by Slasar41** [comment]
Ah sorry it's not a touchscreen but a touchpad.
I'm using ASUS Smart Gesture.

**Comment by Inareous** [comment]
I do use a asus laptop (with asus smart gesture v1.1.1.13) too but I can't reproduce the issue.

All the gesture gets converted by smart gesture as a mouse input to the program. In this case, two fingers to the left should result in a shift + mouse wheel. Try using mouse and scroll using mouse wheel (+ shift for horizontal scroll) to see if the problem exist on mouse too. If it doesn't the problem probably lies on the touchpad converter, however other program like browser shouldn't work too which is kinda impossible. Try other version of asus smart gesture.

**Comment by Slasar41** [comment]
I've same version as yours.
Scrolling with Shift+Mouse Wheel works fine to left and right.
But swipping with two fingers to make the image move to the left will resulting the application to close.
Even when there's no horizontal image so there's no horizontal scrollbar but doing the swipping will get the same result.

**Comment by Inareous** [comment]
After a little bit debugging, this relates to arithmetic overflow on WpfMouseWheelLib.dll which has been [fixed](https://github.com/rvuistin/WpfMouseWheelLib/commit/c13e2c0c982853ec82c2d9d9f02a4a38f6855d61). However the project doesn't create a newer release and the current dll we're using is the first release from it's [codeproject](https://www.codeproject.com/Articles/220255/Improving-WPF-Mouse-Wheel-Processing).

Newly built dll will be shipped in the next release.
