### ISSUE TITLE
Big Size Image

### ISSUE THREAD

**Issue by baskaragilbas** [Inareous/Minimal-CS-Manga-Reader#8]
When opening the album folder, there will be some images that have size that bigger than the view port that will make the viewer horizontal scroll appear. 
Example:
![image](https://user-images.githubusercontent.com/32928834/86451615-5b471680-bd45-11ea-851b-7aba5ba83647.png)

Can you make either one of this feature
1. Automatically resize the oversized picture option. this will make the oversized image to fit the viewport so user  doesn't need to scroll horizontally to see the image 
2. Add horizontal movement to drag feature. Currently user can only do the vertical movement with the drag feature. Also can you add the hotkey for  horizontal scrolling (idk if this already exist or no)?

**Comment by Inareous** [comment]
A small footnote:

I've decided to implement 1 and not 2, however code for 2 is already [available](https://github.com/Inareous/Minimal-CS-Manga-Reader/blob/689cfacee69a3b9d3070d3295ed51c8ded1c5289/Minimal%20CS%20Manga%20Reader/Helper/ScrollHelper.cs#L190) and will be considered if there's enough demand. As of now, dragging horizontally and vertically at the same time is not that satisfying due to bad implementation, however adding a separate hotkey for dragging vertical only, and dragging both (such as left mouse and Ctrl+left mouse) can be a fair band aid i think.
